Fixing some rules & optimizing comp drc table
mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr pull request #40
Opened 2022-12-14 15:35 UTC by FaragElsayed2

- Enhancing the implementation of some drc rules in comp table

2022-12-14 17:07 UTC, atorkmabrains requested changes
@FaragElsayed2 Also, could you comment on speed? It's advisable to run in deep mode.

2022-12-14 17:19 UTC, atorkmabrains requested changes
@FaragElsayed2 please try to fix my comments above.

2022-12-14 17:19 UTC, atorkmabrains commented on rules/klayout/drc/rule_decks/comp.drc
> +    df1a_l1  = comp_56v.not_inside(mvsd.or(mvpsd)).width(0.3.um, euclidian).polygons(0.001)
@FaragElsayed2 it's better performance to do, 'comp_56v.not_inside(mvsd).not_inside(mvpsd) ...' rather than or-ing them

2022-12-14 17:19 UTC, atorkmabrains commented on rules/klayout/drc/rule_decks/comp.drc
@FaragElsayed2 you might need to add forget for all the comp derivations here I think

2022-12-14 18:15 UTC, FaragElsayed2 commented on rules/klayout/drc/rule_decks/comp.drc
> +    df1a_l1  = comp_56v.not_inside(mvsd.or(mvpsd)).width(0.3.um, euclidian).polygons(0.001)
Okay, I will keep that in mind. It will be adapted in next PRs.

2022-12-14 18:18 UTC, FaragElsayed2 commented on rules/klayout/drc/rule_decks/comp.drc
I have added them after their last call. 

For example: 

- ncomp_out_nw_dn.forget was added after df.19
- pcomp_out_nw_dn.forget was added after df.18

And so on

2022-12-14 18:24 UTC, FaragElsayed2 commented
> @FaragElsayed2 Could you please add some screenshots of violations in the description?

Could you please clarify what do you mean by violations here ? Is that mean DRC violations ?

2022-12-14 18:41 UTC, FaragElsayed2 commented
> @FaragElsayed2 Also, could you comment on speed? It's advisable to run in deep mode.

- Before [61 min] 
![comp_before](https://user-images.githubusercontent.com/91015308/207683444-0e95e6a5-87eb-43e6-b8c4-b89072600640.png)

- After [30 min]
![comp_after](https://user-images.githubusercontent.com/91015308/207683573-b3eff915-ee86-454d-836b-0386fb3dd2fc.png)

I think we could optimize it more.

2022-12-14 20:14 UTC, atorkmabrains commented on rules/klayout/drc/rule_decks/comp.drc
> +    df1a_l1  = comp_56v.not_inside(mvsd.or(mvpsd)).width(0.3.um, euclidian).polygons(0.001)
@FaragElsayed2 I haven't approved this. Please change and commit.

2022-12-14 20:15 UTC, atorkmabrains commented
@FaragElsayed2 yes

2022-12-15 08:02 UTC, FaragElsayed2 commented
- Reimplementing DF.13 & DF.14 rules 

![image](https://user-images.githubusercontent.com/91015308/207803388-fd693a5a-3879-4466-b39b-846ad87754f5.png)

- Old implementation used sizing operation to detect maximum separation and this doesn't work for singular cases 

For DF.13_3.3V as example:

- Testing (old imp):
![image](https://user-images.githubusercontent.com/91015308/207804733-868dee00-99ec-4e41-9481-a0abb9cb9428.png)


- Testing (new imp):
![image](https://user-images.githubusercontent.com/91015308/207804882-026fc6fe-290b-4847-8ad9-5dc58a063f70.png)

2022-12-15 08:03 UTC, FaragElsayed2 commented
- More optimization is added for all rules & changes required are added.

2022-12-15 08:28 UTC, atorkmabrains approved these changes
@FaragElsayed2 Thanks for the update

2022-12-15 08:29 UTC, merged